#APP_STL := gnustl_shared
#APP_STL := c++_static
APP_STL := c++_shared
APP_ABI    := arm64-v8a
#APP_CPPFLAGS := --std=gnu++11
#APP_CPPFLAGS := --std=c++11
#NDK_TOOLCHAIN_VERSION := 4.9
##APP_OPTIM := debug
APP_PLATFORM := android-21
APP_OPTIM := release
#APP_PIE := true
